# access the hexo editor directly
local: false

# the username to login hexo editor
username: matt

# the password for logining hexo editor
password: doubi

# the blog directory
base_dir: ~/web/hexo/im

# port
port: 35721
